/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipe.mobilebank.view;

/**
 *
 * @author rodolfo
 */
public class FormAcesso extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frmAcesso
     */
    public FormAcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pbtn = new javax.swing.JPanel();
        btnCE = new javax.swing.JButton();
        btnSis = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 492));

        plogo.setPreferredSize(new java.awt.Dimension(400, 392));
        plogo.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipe/mobilebank/image/logo_acesso.png"))); // NOI18N
        plogo.add(jLabel1, java.awt.BorderLayout.CENTER);

        pbtn.setLayout(new java.awt.GridLayout(1, 0));

        btnCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipe/mobilebank/image/atm.png"))); // NOI18N
        btnCE.setText("Caixa Eletronico");
        btnCE.setBorder(null);
        btnCE.setBorderPainted(false);
        btnCE.setFocusable(false);
        btnCE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCE.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCE.setRequestFocusEnabled(false);
        btnCE.setVerifyInputWhenFocusTarget(false);
        btnCE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        pbtn.add(btnCE);

        btnSis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipe/mobilebank/image/sis.png"))); // NOI18N
        btnSis.setText("Acessar Sistema");
        btnSis.setBorder(null);
        btnSis.setBorderPainted(false);
        btnSis.setFocusable(false);
        btnSis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSis.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSis.setRequestFocusEnabled(false);
        btnSis.setVerifyInputWhenFocusTarget(false);
        btnSis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisActionPerformed(evt);
            }
        });
        pbtn.add(btnSis);

        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setFocusable(false);
        btnSair.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSair.setRequestFocusEnabled(false);
        btnSair.setVerifyInputWhenFocusTarget(false);
        pbtn.add(btnSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisActionPerformed
       FormSistema sistema = new FormSistema();
       sistema.setVisible(true);      
    }//GEN-LAST:event_btnSisActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        FormCaixa formcaixa = new FormCaixa();
        formcaixa.setVisible(true);
    }//GEN-LAST:event_btnCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormAcesso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pbtn;
    private javax.swing.JPanel plogo;
    // End of variables declaration//GEN-END:variables

 
}





